name: RedHook2 Pipeline

on: [push, create]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint Code
      uses: DoozyX/clang-format-lint-action@v0.3.1
      with:
        source: '.'
        exclude: './vendor'
        extensions: 'h,hpp,c,cpp'
  
  test:
    runs-on: windows-latest
    needs: lint
    steps:
    - uses: actions/checkout@v1
    - name: Test Project
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" RedHook2.sln
  
  build:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Compile Project
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" -m -p:Configuration=Release RedHook2.sln
    - name: Upload RedHook2.dll
      uses: actions/upload-artifact@master
      with:
        name: RedHook2
        path: build/Release/RedHook2.dll
    - name: Upload RedHook2.lib
      uses: actions/upload-artifact@master
      with:
        name: RedHook2-lib
        path: build/Release/RedHook2.lib
    - name: Upload Loader
      uses: actions/upload-artifact@master
      with:
        name: Loader
        path: build/Release/Loader.exe
        
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Download RedHook2.dll Artifact
        uses: actions/download-artifact@master
        with:
          name: RedHook2
      - name: Download RedHook2.lib Artifact
        uses: actions/download-artifact@master
        with:
          name: RedHook2-lib
      - name: Download Loader.exe Artifact
        uses: actions/download-artifact@master
        with:
          name: Loader
      - name: Package Files
        run: |
          zip -j RedHook2.zip RedHook2/RedHook2.dll Loader/Loader.exe
          mkdir inc
          mkdir lib
          mv source/export.hpp inc/redhook2.h
          mv RedHook2-lib/RedHook2.lib lib/RedHook2.lib
          zip RedHook2-lib.zip lib/RedHook2.lib inc/redhook2.h
      - name: Release Package
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedHook2.zip
          asset_name: RedHook2.zip
          asset_content_type: application/zip
      - name: Release Developer Package
        id: upload-developer-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedHook2-lib.zip
          asset_name: RedHook2-lib.zip
          asset_content_type: application/zip
